//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallpaperMaker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("330999996666001199999999999")]
        public string Seed {
            get {
                return ((string)(this["Seed"]));
            }
            set {
                this["Seed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""Pallets"": [
    {
      ""Pallet"": {
        ""Name"": ""Sample Pallet"",
        ""Colors"": [
          ""229,244,227"",
          ""93,169,233"",
          ""0,63,145"",
          ""255,255,255"",
          ""109,50,109""
        ]
      }
    },
    {
      ""Pallet"": {
        ""Name"": ""Another Pallet"",
        ""Colors"": [
          ""109,238,170"",
          ""183,209,18"",
          ""216,236,126"",
          ""210,64,22"",
          ""177,107,7""
        ]
      }
    }
  ]
}")]
        public string UserColorPallets {
            get {
                return ((string)(this["UserColorPallets"]));
            }
            set {
                this["UserColorPallets"] = value;
            }
        }
    }
}
